#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Nov 27 14:51:14 IST 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_uart_rx_behav -key {Behavioral:sim_1:Functional:tb_uart_rx} -tclbatch tb_uart_rx.tcl -view /home/shubhayu/Sem 7/FPGA/Vivado/UART_RX_TX/UART_RX_TX.srcs/sim_1/imports/UART_115200/tb_uart_rx_behav.wcfg -log simulate.log"
xsim tb_uart_rx_behav -key {Behavioral:sim_1:Functional:tb_uart_rx} -tclbatch tb_uart_rx.tcl -view /home/shubhayu/Sem 7/FPGA/Vivado/UART_RX_TX/UART_RX_TX.srcs/sim_1/imports/UART_115200/tb_uart_rx_behav.wcfg -log simulate.log

