#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Nov 29 00:57:54 IST 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_controller_behav -key {Behavioral:controller_sim:Functional:tb_controller} -tclbatch tb_controller.tcl -view /home/shubhayu/Sem 7/FPGA/Vivado/UART_RX_TX/tb_controller_behav.wcfg -log simulate.log"
xsim tb_controller_behav -key {Behavioral:controller_sim:Functional:tb_controller} -tclbatch tb_controller.tcl -view /home/shubhayu/Sem 7/FPGA/Vivado/UART_RX_TX/tb_controller_behav.wcfg -log simulate.log

